util: Fix build on macOS
tests/util/piglit-util.c:554:13: error: no member named 'st_mtim' in 'struct stat'
  554 |         if (stat_a.st_mtim.tv_sec < stat_b.st_mtim.tv_sec ||
      |             ~~~~~~ ^
tests/util/piglit-util.c:554:37: error: no member named 'st_mtim' in 'struct stat'
  554 |         if (stat_a.st_mtim.tv_sec < stat_b.st_mtim.tv_sec ||
      |                                     ~~~~~~ ^
tests/util/piglit-util.c:555:14: error: no member named 'st_mtim' in 'struct stat'
  555 |             (stat_a.st_mtim.tv_sec == stat_b.st_mtim.tv_sec &&
      |              ~~~~~~ ^
tests/util/piglit-util.c:555:39: error: no member named 'st_mtim' in 'struct stat'
  555 |             (stat_a.st_mtim.tv_sec == stat_b.st_mtim.tv_sec &&
      |                                       ~~~~~~ ^
tests/util/piglit-util.c:556:14: error: no member named 'st_mtim' in 'struct stat'
  556 |              stat_a.st_mtim.tv_nsec < stat_b.st_mtim.tv_nsec))
      |              ~~~~~~ ^
tests/util/piglit-util.c:556:39: error: no member named 'st_mtim' in 'struct stat'
  556 |              stat_a.st_mtim.tv_nsec < stat_b.st_mtim.tv_nsec))
      |                                       ~~~~~~ ^

Fixes: 701843aa2 ("util: add piglit_is_file_older_than helper")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Timothy Arceri <tarceri@itsqueeze.com>
Part-of: <https://gitlab.freedesktop.org/mesa/piglit/-/merge_requests/1031>